name: food_ordering_project
services:
  staff_frontend:
    image: nathapatt/ordering-food-staff
    container_name: food_ordering_staff_frontend
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_API_PROXY_PATH=${VITE_API_PROXY_PATH}
      - VITE_CUSTOMER_FRONTEND_URL=${VITE_CUSTOMER_FRONTEND_URL}
    ports:
      - '${PORT}:80'
    networks:
      - food_ordering_project_food_ordering_network
    restart: unless-stopped

networks:
  food_ordering_project_food_ordering_network:
    external: true
      